# Import external theme files
# import = [ "~/.config/alacritty/themes/themes/my_custom_theme.toml" ]

# Window settings
[window]
padding.x = 15
padding.y = 15
dynamic_padding = true
decorations = "Buttonless" # "Full", "Buttonless", "Transparent", "None"
opacity = 1.0
blur = true # Only works on macOS
dimensions.columns = 120
dimensions.lines = 30
position.x = 100
position.y = 50

# Font settings
[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

# Scrolling settings
[scrolling]
history = 10000 # Number of lines in scrollback buffer
multiplier = 3 # Scroll speed multiplier

# Cursor settings
[cursor]
style = "Block" # "Block", "Underline", "Beam"
blink_interval = 500 # Milliseconds

# Key bindings
[keyboard]
bindings = [
  { key = "Paste", mods = "Control|Shift", action = "Paste" },
  { key = "Copy", mods = "Control|Shift", action = "Copy" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
]

