set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

set -g @tmux-gruvbox 'dark256'

# Copiar seleção do mouse para clipboard do macOS
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

run-shell '~/.tmux/plugins/tpm/tpm'
